---
title: "Aula 11"
format: html
editor: visual
---

Aula 11 - 19/06/2024

**Criando mapas no R**

**Pacotes**

```{r}
library(gsheet)
library(tidyverse)
library(remotes)
library(rnaturalearth)
library(r4pde)
library(ggthemes)
library(ggspatial)
library(plotly)
library(leaflet)
library(ggrepel)
library(scatterpie)
```

**Istalando pacotes do repositorio github:**

```{r}
remotes::install_github("ropensci/rnaturalearthhires")
```

```{r}
BRA <- ne_states (country = "Brazil",
                  returnclass = "sf")

world <- ne_countries()

sbr <- RustSoybean

ggplot(BRA) + geom_sf(fill = "white", color = "blue", linewidth = 1) +
  geom_point(data = sbr, aes(longitude, latitude), color ="black") + theme_map()
```

```{r}
sbr <- RustSoybean

sbr |> 
  ggplot(aes(longitude, latitude)) +
  geom_point()+coord_sf()
```

```{r}
BRA <- ne_states (country = "Brazil",
                  returnclass = "sf")
MG <- BRA |> 
  filter(name_en == "Minas Gerais")
bra <- ggplot(BRA) +
  geom_sf(fill = "white", color = "blue", linewidth = 0.5) +
  geom_point(data = MG, aes(longitude, latitude), color ="red") + theme_map() +
  annotation_north_arrow(which_north = "grid")
```

Para criar um objeto BRA no ggplot

```{r}
library(plotly)
ggplotly(bra)
```

Para criar um mapa realista:

```{r}
vicosa <- leaflet() |> 
  addTiles() |> 
  addProviderTiles(providers$Esri.NatGeoWorldMap) |>
  setView(lng = -42.8825, lat = -20.7546, zoom = 5)
vicosa
```

```{r}
vicosa <- leaflet(sbr) |> 
  addTiles() |> 
  #addProviderTiles(providers$Esri.NatGeoWorldMap) |>
  #setView(lng = -42.8825, lat = -20.7546, zoom = 5) |> 
  addCircleMarkers(radius = 2)
vicosa
```

```{r}
Viçosa <- leaflet() |> 
  addTiles() |> 
  setView(lng = -42.8825, lat = - 20.7546, zoom = 15)
Viçosa
```

Para usar um grafico de pizza, muito usado para demosntrar genotipos.

```{r, warning=FALSE}
mapa <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1pAIFKsdKxk_UQQXdYwIO-O5NOkYNhpclImJcLziYnk4/edit?usp=sharing")

ggplot(BRA) +
  geom_sf(fill = "gray70", alpha = 0.5, color = "white") +
  coord_sf()+
  geom_scatterpie(aes(x = lon, y = lat, r = 0.6), alpha = 0.8, color = NA, data = mapa,
                  cols = c("DFC",
                           "MA",
                           "FER",
                           "ANTR",
                           "OIDIO"))+
  geom_text_repel(data = mapa, aes(lon, lat, label = Local),
                   size = 2, nudge_x = 0.2, nudge_y = 0.27, color = "gray30", family = "Arial") +
  ggthemes::scale_fill_calc()+
  ggthemes::theme_map() +
  labs(x = "Longitude", y = "Latitude", legend = "", fill = "Doença")+
  theme(legend.position = "bottom", text = element_text(family = "Arial", size = 8))

```
